@port = 4000
@host = http://localhost:{{port}}
@apiUrl = {{host}}/api

### 

# -*******************************************************************************-
# AUTH ROUTES
# Register a student
POST {{apiUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "Maria",
    "email": "maria@gmail.com",
    "password": "Maria12345",
    "user_roles_id": 2,
    "topicIds": [3, 4]
}

###
# Log in as student
POST {{apiUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "juanpablo@gmail.com",
    "password": "Juanpablo12345"
}

###
# Log in as instructor
POST {{apiUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "omar@gmail.com",
    "password": "Omar12345"
}

###
# Log in as admin
POST {{apiUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "dagutmu667@gmail.com",
    "password": "Dan12345"
}

###
# Verify token (JWT)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzE2OTE4MTUxLCJleHAiOjE3MTY5MjE3NTF9.PF2qh6HbIBjg0zEDLDjZSyItf8N9l_M-NHEaGhoFa3M
POST {{apiUrl}}/auth/verify-token HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### -*******************************************************************************-

### -*******************************************************************************-
# COURSES ROUTES
# Get student or instructor courses
GET {{apiUrl}}/courses HTTP/1.1
Authorization: Bearer {{token}}